import type {Metadata} from "next";

import "./globals.css";
import Link from "next/link";
import {Inter} from "next/font/google";
import {Suspense} from "react";

import {ListItem, ListItemLoading} from "./ui/listitem";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Uizard Hacerknews Reader",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const posts = await fetch(`https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty"`)
    .then((resp) => resp.json() as Promise<number[]>)
    .then((data) => data.slice(data.length - 15, data.length));

  return (
    <html lang="en">
      <body className={`${inter.className} grid h-screen grid-rows-[60px,1fr]`}>
        <header className="grid place-content-center bg-yellow-400 text-xl font-bold text-black">
          <Link href="/">
            <h1>Uizard Hacerknews Reader</h1>
          </Link>
        </header>
        <main className="grid grid-cols-[320px,1fr] overflow-hidden">
          <aside className="h-full overflow-y-scroll">
            <ul className="flex flex-col gap-4 p-4">
              {posts.map((id) => (
                <Link key={id} href={`/${id}`}>
                  <Suspense fallback={<ListItemLoading />}>
                    {/* @ts-expect-error Server Component */}
                    <ListItem id={id} />
                  </Suspense>
                </Link>
              ))}
            </ul>
          </aside>
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
